#!/usr/bin/env bash
#Displays "bad luck" on 4th loop, "good luck" on the 8th and best school on others 
COUNTER=0
while [ $COUNTER -lt 10 ];
do
	if [ $COUNTER -eq 3 ]
	then
echo "bad luck"
	elif [ $COUNTER -eq 7 ]
	then
echo "good luck"
	else
echo "Best School"
	fi
	COUNTER=$((COUNTER+1))
done
